server:
  port: 8671
  tomcat:
    uri-encoding: UTF-8


spring:
  application:
    name: schedule-admin
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  main:
    allow-bean-definition-overriding: true
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      number_format: 0.##########
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      classic_compatible: true
      template_exception_handler: ignore
  mvc:
    static-path-pattern: /static/**


logging:
  config: classpath:logback.xml


netty:
  url: 127.0.0.1
  port: 10125


jdbc:
  url: jdbc:mysql://127.0.0.1:3306/wjs_schedule?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&connectTimeout=1000&socketTimeout=6000&useSSL=false&serverTimezone=UTC
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: root


cuckoo:
  pending:
    job:
      retry: 30000